-- DROP TABLE IF EXISTS site;

CREATE TABLE IF NOT EXISTS site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    status VARCHAR(30) DEFAULT 'A',
    response_time BIGINT DEFAULT 0,
    enabled BOOLEAN DEFAULT TRUE,
    assert_text VARCHAR(2000),
    failures BIGINT DEFAULT 0,
    failure_limit BIGINT DEFAULT 3,
    notify VARCHAR(500),
    last_notification VARCHAR(500),
    last_checked TIMESTAMP,
    -- Change Event collection
    event_time TIMESTAMP,
    event_description VARCHAR(1000),
    event_change VARCHAR(30) DEFAULT 'NO'
);

-- INSERT INTO site (name,url,status,assert_text,notify) VALUES ('Site Monitor 2 (localhost)','http://localhost:8080/actuator/health','OK','UP','alerts@test.net');
-- COMMIT;
